- src/lucky_migrator/tasks/db/create.cr
- src/lucky_migrator/tasks/db/drop.cr
> Focus on the important parts in output

- spec/create_table_statement_spec.cr
- src/lucky_migrator/create_table_statement.cr
#19 - I just set the defaults timestamptz. This doesn't include any options to set it back to timestamp.
Also I agree the default timezone should be UTC, but I'm not sure how to set that. I can look at it tomorrow.
> Set default time columns to timestamptz

- spec/create_index_statement_spec.cr
- spec/create_table_statement_spec.cr
- src/lucky_migrator/create_index_statement.cr
- src/lucky_migrator/create_table_statement.cr
* Make just one method for getting the statements
* Change tests to use the `statements` method
@mikeeus you may be interested in seeing this
> Make statements method for CreateTableStatement

- db/migrations/001_create_users.cr
- spec/create_index_statement_spec.cr
- src/lucky_migrator/create_index_statement.cr
- src/lucky_migrator/statement_helpers.cr
Needs to handle duplicate indexes as stated in #27
> Extract add index

- db/migrations/001_create_users.cr
- db/migrations/003_create_comments.cr
- src/lucky_migrator/statement_helpers.cr
> Rename add_index to create_index, update migrations

- src/lucky_migrator/runner.cr
- src/lucky_migrator/tasks/db/redo.cr
Closes #40.
The redo command simply calls `rollback_one` then `run_pending_migrations`.
> Add redo command

- src/lucky_migrator/runner.cr
- src/lucky_migrator/tasks/db/migrate_one.cr
Closes #49.
I named the command `migrate_one` because I wasn't sure how to make it `migrate.one`.
The command checks for the first pending migration and runs it if it exists.
> Add lucky db.migrate_one command

- .circleci/config.yml
> Run on Circle CI

- db/migrations/002_alter_users.cr
- spec/change_null_statement_spec.cr
- src/lucky_migrator/change_null_statement.cr
- src/lucky_migrator/statement_helpers.cr
> Change null statement

- .circleci/config.yml
- src/lucky_migrator/runner.cr
- src/lucky_migrator/tasks/db/create.cr
- src/lucky_migrator/tasks/gen/migration.cr
- src/lucky_migrator/tasks/gen/migration.ecr
> Create migrations with a constant

- src/lucky_migrator.cr
- src/lucky_migrator/tasks/db/create.cr
- src/lucky_migrator/tasks/db/drop.cr
- src/lucky_migrator/tasks/db/migrate.cr
- src/lucky_migrator/tasks/db/migrate_one.cr
- src/lucky_migrator/tasks/db/rollback.cr
- src/lucky_migrator/tasks/db/rollback_all.cr
- src/lucky_migrator/tasks/gen/migration.cr
> Handle errors gracefully in all tasks

- src/lucky_migrator/runner.cr
> Gracefully handle db.create/drop

- spec/alter_table_statement_spec.cr
- src/lucky_migrator/alter_table_statement.cr
Closes #64.
I just realized I was naming my branches incorrectly, so now it's [initials]-[issue]-[name].
> Disallow both default and fill_existing_with argments

- src/lucky_migrator/runner.cr
Closes #67.
I added an error message for the error on linux machines.
> Add helpful messages on missing createdb command

- README.md
> Add testing section and contributor

- spec/create_table_statement_spec.cr
- src/lucky_migrator/create_table_statement.cr
> Use Int32 on belongs_to association

- spec/alter_table_statement_spec.cr
- src/lucky_migrator/alter_table_statement.cr
* Raise compile time errors for missing options
* Add fill_existing_with: :nothing
> Improve fill_existing_with

- src/lucky_migrator/runner.cr
if can't access database server, instruction message has typo
> Fix typo udpate to update

- src/lucky_migrator/runner.cr
Hello,
I tried to create a docker-compose file to run my lucky webapp and noticed that createdb and dropdb only works on local postgresql.
This pull request changes the behaviour of this two tasks and allow the usage of them with remote postgresql servers.
> Use database url config in create and drop db.

- src/lucky_migrator/runner.cr
Hi, just added a lil bit of error handling after speding some time trying to understand what was happening in the issue luckyframework/lucky#388.
Hope you find useful as it could help users detect quickly what might be going on.
Regards
> Added bit more detail to migration failures as in luckyframework/lucky#388

- .circleci/config.yml
- shard.yml
- src/lucky_migrator/version.cr
* Use Lucky master for v0.25
* Update Circle
> Use Lucky master for v0.25 (#109)

- spec/create_table_statement_spec.cr
- src/lucky_migrator/create_table_statement.cr
- src/lucky_migrator/primary_key_type.cr
- src/lucky_migrator/statement_helpers.cr
This is the companion for https://github.com/luckyframework/lucky_record/pull/254.
> Allow setting the primary key type

- src/lucky_migrator/tasks/gen/migration.ecr
In lieu of documentation fix as well :)
> Properly indent commented migration sample, closes #89

- spec/create_table_statement_spec.cr
- src/lucky_migrator.cr
- src/lucky_migrator/column_type_option_helpers.cr
Keepin' the PRs tiny here. This allows you to manually add a reference column, or just generally a uuid column.
> Support uuid column types
